package xyz.swwarehouse.daemon.sample;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class OperationTest {
	@Test
	public void testIncreatmentNumMethod() {
		Operation op = new Operation();
		int n = 0;
		assertEquals(n + 1, op.increatmentNum(n));
	}
}
